version: 2

run:
  timeout: 5m
  tests: true
  out-format: colored-line-number

linters:
  enable:
    # Core
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

    # Error discipline
    - errorlint
    - wrapcheck

    # Style
    - revive

    # Security
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
  linters-settings:
    govet:
      check-shadowing: true
    revive:
      rules:
        - name: var-naming
        - name: line-length-limit
          arguments: [ 120 ]
        - name: unexported-return
        - name: blank-imports
        - name: error-strings
        - name: error-naming

  gosec:
    excludes:
      - G104
      - G307

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

exclude-dirs:
  - vendor
  - node_modules
  - dist
  - tmp

exclude-files:
  - ".*\\.gen\\.go"
  - ".*_mock\\.go"

exclude-rules:
  - path: _test\\.go
    linters:
      - errcheck
      - gosec

severity:
  default-severity: error
