version: 2
run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Core correctness
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

    # Error handling
    - errorlint
    - wrapcheck

    # Security
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: line-length-limit
        arguments: [ 120 ]
      - name: unexported-return
      - name: blank-imports
      - name: error-strings
      - name: error-naming

  gosec:
    excludes:
      - G104
      - G307
      - ST1005
      - QF1012

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - node_modules
    - dist
    - tmp
    - .git

  exclude-files:
    - ".*\\.gen\\.go"
    - ".*_mock\\.go"

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: .*\.gen\.go
      linters:
        - revive

severity:
  default-severity: error
